# Generated by Django 5.2.4 on 2025-08-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_catalog_pro_price_2d2a4c_idx_and_more'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product'], name='order_order_product_ed1645_idx'),
        ),
    ]
